# Generated by Django 5.0.7 on 2024-07-24 18:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blogs", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={"verbose_name_plural": "posts"},
        ),
        migrations.RenameField(
            model_name="post",
            old_name="topic",
            new_name="blog",
        ),
    ]
