# Generated by Django 5.0.7 on 2024-07-17 18:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pizzas", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="topping",
            options={"verbose_name_plural": "toppings"},
        ),
    ]
